project: "hutech_mushroom"
dataset: "hutech-dataset:latest"
model: "regnet"
# technique
freeze: False

# augmentation
resize: 224
random_crop: 224
horizontal_flip: 0.5
vertical_flip: 0.5
random_rotation: 90
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.2
# random_affine: 0.2
# gray: 0.2
# random_perspective: 0.2
# blur: 1
# auto_aug: 1

normalize: 1
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
random_erasing: 0.2

# optimizier: schedule + earlystopping
scheduler: "cosine"
es_patience: 10

# hyperparameters
num_classes: 4
lr: 1e-5
num_epochs: 30
batch_size: 4
optimizer: "adam"
weight_decay: 0.00025
momentum: 0.9
