project: "hutech_mushroom"
dataset: "hutech-dataset:latest"
model: "vit"
# technique
freeze: True

# augmentation
resize: 224
random_crop: 224
horizontal_flip: 0.5
vertical_flip: 0.5
random_rotation: 90
brightness: 0.5
contrast: 0.5
saturation: 0.5
hue: 0.5
random_affine: 0.5
random_perspective: 0.5
auto_aug: 1

normalize: 1
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
random_erasing: 0.3

# optimizier: schedule + earlystopping
scheduler: "cosine"
es_patience: 10

# hyperparameters
num_classes: 4
lr: 1e-5
num_epochs: 150
batch_size: 4
optimizer: "adam"
weight_decay: 0.00025
momentum: 0.9
