project: "hutech_mushroom"
dataset: "hutech-dataset:latest"
model: "vit"
# technique
pretrained: true
freeze: false

# augmentation
resize: 224
horizontal_flip: 0.5
vertical_flip: 0.5
random_rotation: 90
# brightness: 0.2
# contrast: 0.2
# saturation: 0.2
# hue: 0.1
random_affine: 0.2
random_perspective: 0.2

auto_aug: 1

normalize: 0
# mean: [0.485, 0.456, 0.406]
# std: [0.229, 0.224, 0.225]
# random_erasing: 0.5

# optimizier: schedule + earlystopping
scheduler: "step"
es_patience: 10

# hyperparameters
num_classes: 4
lr: 1e-5
num_epochs: 150
batch_size: 8
optimizer: "adamw"
weight_decay: 0.00025
momentum: 0.9