project: "hutech_mushroom"
dataset: "hutech-dataset:latest"
model: "convnext"
# technique
pretrained: true
freeze: false

# augmentation
resize: 224
horizontal_flip: 0.5
vertical_flip: 0.5
random_rotation: 90
# brightness: 0.2
# contrast: 0.2
# saturation: 0.2
# hue: 0.1
random_affine: 0.2
random_perspective: 0.2

auto_aug: 1

normalize: 0
# mean: [0.485, 0.456, 0.406]
# std: [0.229, 0.224, 0.225]
random_erasing: 0.1

# optimizier: schedule + earlystopping
scheduler: "step"
is_warmup: true
lr: 0.01

## StepLR
scheduler_step: 30
scheduler_gamma: 0.1
scheduler_warmup: 0.05
## Cosine (default)
## EarlyStopping
es_patience: 20

# hyperparameters
num_classes: 4
num_epochs: 150
batch_size: 8
optimizer: "adamw"
loss: "cross_entropy"
is_weight: true
weight_decay: 0.00025
momentum: 0.9