project: "hutech_mushroom"
dataset: "hutech-dataset:latest"
model: "alexnet"

# augmentation
resize: 224
horizontal_flip: 0.5
vertical_flip: 0.5
random_rotation: 90
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.2
kernel_size: [3, 3]
sigma: [0.1, 3.0]

# optimizier: schedule + earlystopping
scheduler: "reduce_lr_on_plateau"
es_patience: 10

# hyperparameters
num_classes: 4
lr: 1e-5
num_epochs: 1
batch_size: 4
optimizer: "adam"
weight_decay: 0.0001
momentum: 0.9
