program: train.py
name: aug_sweep
method: grid
metric:
  name: test_accuracy
  goal: maximize
parameters:
  model:
    value: "alexnet"
  dataset:
    value: "hutech-dataset:latest"
  # augmentation (sweep)
  resize:
    values: [224]
  horizontal_flip:
    values: [0, 224]
  vertical_flip:
    values: [0, 0.5]
  random_rotation:
    values: [0, 90]
  brightness:
    values: [0, 0.2]
  contrast:
    values: [0, 0.2]
  saturation:
    values: [0, 0.2]
  hue:
    values: [0, 0.2]
  # hyperparameters (fixed)
  num_classes:
    value: 4
  lr:
    value: 1e-5
  num_epochs:
    value: 30
  batch_size:
    value: 4
  optimizer:
    value: "adam"
  weight_decay:
    value: 0.0001
  momentum:
    value: 0.9
    
command:
  - ${env}
  - python
  - ${program}