program: train.py
name: model_sweep
method: grid
metric:
  name: test_accuracy
  goal: maximize
parameters:
  # model (sweep)
  model:
    values: ["alexnet", "convnext", "densenet", "efficientnet", "mobilenet", "resnet", "vit", "regnet"]
  dataset:
    value: "hutech-dataset:latest"
  freeze:
    values: [True]
  # augmentation (fixed)
  resize:
    values: [224]
  horizontal_flip:
    values: [0.5]
  vertical_flip:
    values: [0.5]
  random_rotation:
    values: [90]
  brightness:
    values: [0.2]
  contrast:
    values: [0.2]
  saturation:
    values: [0.2]
  hue:
    values: [0.2]
  normalize: 
    value: 1
  mean:
    value: [0.485, 0.456, 0.406]
  std:
    value: [0.229, 0.224, 0.225]
  # hyperparameters (fixed)
  num_classes:
    value: 4
  lr:
    value: 1e-5
  num_epochs:
    value: 150
  batch_size:
    value: 4
  optimizer:
    value: "adam"
  scheduler: 
    value: "cosine"
  es_patience: 
    value: 10
  weight_decay:
    value: 0.00025
  momentum:
    value: 0.9
    
command:
  - ${env}
  - python
  - ${program}