program: train.py 
method: bayes
metric:
  name: test_accuracy
  goal: maximize
parameters:
  model: 
    value: "alexnet"
  dataset: 
    value: "hutech-dataset:latest"
  lr:
    distribution: categorical
    values:
      - 0.00001
      - 0.0001
      - "1e-5"
  momentum:
    distribution: uniform
    min: 0.45
    max: 1.8
  optimizer:
    distribution: categorical
    values:
      - adam
      - sgd
      - adamw
  batch_size: 
    values: [2, 4, 8, 16, 32, 64]
  num_epochs: 
    values: [30, 50, 70, 100]
  weight_decay:
    distribution: uniform
    min: 0.00005
    max: 0.0002

  ## augmentation
  resize:
    values: [224]
  horizontal_flip:
    values: [0.5]
  vertical_flip:
    values: [0.5]
  random_rotation:
    values: [90]
  brightness:
    values: [0.2]
  contrast:
    values: [0.2]
  saturation:
    values: [0.2]
  hue:
    values: [0.2]

command:
  - ${env}
  - python
  - ${program}